import mysql from 'mysql2/promise';

export const name = '001_initial_schema';

export async function up(conn: mysql.Connection): Promise<void> {
  const queries: string[] = [
    `CREATE TABLE IF NOT EXISTS departments (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) UNIQUE NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL
    )`,
    `CREATE TABLE IF NOT EXISTS roles (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(50) UNIQUE NOT NULL,
      slug VARCHAR(50) UNIQUE NOT NULL,
      description TEXT,
      is_system BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS permissions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      slug VARCHAR(100) UNIQUE NOT NULL,
      description TEXT,
      module VARCHAR(50) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS role_permissions (
      role_id INT NOT NULL,
      permission_id INT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (role_id, permission_id),
      FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
      FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(50) UNIQUE NOT NULL,
      password VARCHAR(255) NOT NULL,
      email VARCHAR(100) UNIQUE,
      first_name VARCHAR(100) NOT NULL,
      last_name VARCHAR(100) NOT NULL,
      photo VARCHAR(500),
      phone VARCHAR(20),
      gender VARCHAR(10),
      address TEXT,
      date_of_birth DATE,
      role_id INT NOT NULL,
      department_id INT,
      is_active BOOLEAN DEFAULT TRUE,
      failed_attempts INT DEFAULT 0,
      locked_until TIMESTAMP NULL,
      last_login TIMESTAMP NULL,
      refresh_token TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (role_id) REFERENCES roles(id),
      FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS employees (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT UNIQUE NOT NULL,
      employee_code VARCHAR(250) UNIQUE NOT NULL,
      national_id VARCHAR(50),
      position VARCHAR(100),
      employment_type VARCHAR(50),
      salary DECIMAL(12,2),
      date_hired DATE,
      supervisor_id INT,
      status VARCHAR(20) DEFAULT 'active',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (supervisor_id) REFERENCES employees(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS sessions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL,
      token TEXT NOT NULL,
      expires_at TIMESTAMP NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS notifications (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL,
      type VARCHAR(20) NOT NULL,
      title VARCHAR(200) NOT NULL,
      message TEXT NOT NULL,
      is_read BOOLEAN DEFAULT FALSE,
      link VARCHAR(500),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS tasks (
      id INT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(200) NOT NULL,
      description TEXT,
      priority VARCHAR(20) DEFAULT 'medium',
      assigned_by_id INT NOT NULL,
      assigned_to_id INT NOT NULL,
      due_date TIMESTAMP NULL,
      status VARCHAR(20) DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (assigned_by_id) REFERENCES users(id),
      FOREIGN KEY (assigned_to_id) REFERENCES users(id)
    )`,
    `CREATE TABLE IF NOT EXISTS activity_logs (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT,
      action VARCHAR(200) NOT NULL,
      module VARCHAR(50),
      description TEXT,
      ip_address VARCHAR(50),
      user_agent VARCHAR(500),
      previous_values JSON,
      new_values JSON,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS login_history (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id INT NOT NULL,
      ip_address VARCHAR(50),
      user_agent VARCHAR(500),
      device VARCHAR(100),
      browser VARCHAR(100),
      os VARCHAR(100),
      status VARCHAR(20) DEFAULT 'success',
      login_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      logout_at TIMESTAMP NULL,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS branches (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      code VARCHAR(20) UNIQUE NOT NULL,
      address TEXT,
      phone VARCHAR(20),
      email VARCHAR(100),
      currency VARCHAR(10) DEFAULT 'RWF',
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL
    )`,
    `CREATE TABLE IF NOT EXISTS positions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      department_id INT NOT NULL,
      description TEXT,
      requirements TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS leave_types (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      days_allowed INT NOT NULL,
      is_paid BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS attendance (
      id INT AUTO_INCREMENT PRIMARY KEY,
      employee_id INT NOT NULL,
      date DATE NOT NULL,
      check_in TIME,
      check_out TIME,
      status VARCHAR(50) DEFAULT 'present',
      late_minutes INT DEFAULT 0,
      overtime_minutes INT DEFAULT 0,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS contracts (
      id INT AUTO_INCREMENT PRIMARY KEY,
      employee_id INT NOT NULL,
      contract_type VARCHAR(50) NOT NULL,
      start_date DATE NOT NULL,
      end_date DATE,
      salary DECIMAL(12,2),
      document_url VARCHAR(500),
      status VARCHAR(50) DEFAULT 'active',
      signed_by_employee BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS documents (
      id INT AUTO_INCREMENT PRIMARY KEY,
      employee_id INT NOT NULL,
      document_type VARCHAR(100) NOT NULL,
      document_name VARCHAR(200) NOT NULL,
      file_url VARCHAR(500),
      expiry_date DATE,
      uploaded_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
      FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS trainings (
      id INT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(200) NOT NULL,
      description TEXT,
      trainer VARCHAR(200),
      start_date DATE,
      end_date DATE,
      status VARCHAR(50) DEFAULT 'planned',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS training_participants (
      id INT AUTO_INCREMENT PRIMARY KEY,
      training_id INT NOT NULL,
      employee_id INT NOT NULL,
      status VARCHAR(50) DEFAULT 'enrolled',
      score INT,
      certificate_url VARCHAR(500),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (training_id) REFERENCES trainings(id) ON DELETE CASCADE,
      FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS performance_reviews (
      id INT AUTO_INCREMENT PRIMARY KEY,
      employee_id INT NOT NULL,
      reviewer_id INT NOT NULL,
      review_date DATE NOT NULL,
      score DECIMAL(5,2),
      rating VARCHAR(50),
      comments TEXT,
      goals TEXT,
      next_review_date DATE,
      status VARCHAR(50) DEFAULT 'draft',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
      FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS salary_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      employee_id INT NOT NULL,
      basic_salary DECIMAL(12,2),
      allowances DECIMAL(12,2) DEFAULT 0.00,
      deductions DECIMAL(12,2) DEFAULT 0.00,
      net_salary DECIMAL(12,2),
      month VARCHAR(7) NOT NULL,
      payment_date DATE,
      status VARCHAR(50) DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS employee_history (
      id INT AUTO_INCREMENT PRIMARY KEY,
      employee_id INT NOT NULL,
      action VARCHAR(50) NOT NULL,
      description TEXT,
      old_value TEXT,
      new_value TEXT,
      changed_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
      FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS leave_requests (
      id INT AUTO_INCREMENT PRIMARY KEY,
      employee_id INT NOT NULL,
      leave_type_id INT NOT NULL,
      start_date DATE NOT NULL,
      end_date DATE NOT NULL,
      reason TEXT,
      status VARCHAR(50) DEFAULT 'pending',
      approved_by INT,
      approved_at TIMESTAMP NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
      FOREIGN KEY (leave_type_id) REFERENCES leave_types(id) ON DELETE CASCADE,
      FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS recruitment_jobs (
      id INT AUTO_INCREMENT PRIMARY KEY,
      position_id INT NOT NULL,
      title VARCHAR(200) NOT NULL,
      description TEXT,
      requirements TEXT,
      status VARCHAR(50) DEFAULT 'draft',
      posted_date DATE,
      closing_date DATE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (position_id) REFERENCES positions(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS applicants (
      id INT AUTO_INCREMENT PRIMARY KEY,
      job_id INT NOT NULL,
      first_name VARCHAR(100) NOT NULL,
      last_name VARCHAR(100) NOT NULL,
      email VARCHAR(100),
      phone VARCHAR(20),
      resume_url VARCHAR(500),
      status VARCHAR(50) DEFAULT 'applied',
      interview_date TIMESTAMP NULL,
      interview_notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (job_id) REFERENCES recruitment_jobs(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS animal_categories (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS animal_locations (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      type VARCHAR(50) DEFAULT 'other',
      capacity INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS animal_groups (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL
    )`,
    `CREATE TABLE IF NOT EXISTS breeds (
      id INT AUTO_INCREMENT PRIMARY KEY,
      category_id INT NOT NULL,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (category_id) REFERENCES animal_categories(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS animals (
      id INT AUTO_INCREMENT PRIMARY KEY,
      tag_number VARCHAR(50) UNIQUE NOT NULL,
      name VARCHAR(100),
      animal_category_id INT NOT NULL,
      breed_id INT,
      gender VARCHAR(10),
      color VARCHAR(50),
      date_of_birth DATE,
      age INT,
      weight DECIMAL(10,2),
      height DECIMAL(10,2),
      photo_url VARCHAR(500),
      source VARCHAR(50) DEFAULT 'born',
      purchase_price DECIMAL(12,2),
      location_id INT,
      group_id INT,
      status VARCHAR(50) DEFAULT 'active',
      is_dairy BOOLEAN DEFAULT FALSE,
      lactation_number INT DEFAULT 0,
      milk_status VARCHAR(50),
      feed_type VARCHAR(50),
      animal_status VARCHAR(50),
      photo VARCHAR(500),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (animal_category_id) REFERENCES animal_categories(id) ON DELETE CASCADE,
      FOREIGN KEY (breed_id) REFERENCES breeds(id) ON DELETE SET NULL,
      FOREIGN KEY (location_id) REFERENCES animal_locations(id) ON DELETE SET NULL,
      FOREIGN KEY (group_id) REFERENCES animal_groups(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS breeding_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      mother_id INT NOT NULL,
      father_id INT,
      breeding_date DATE NOT NULL,
      method VARCHAR(50) DEFAULT 'natural',
      result VARCHAR(50) DEFAULT 'pending',
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (mother_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (father_id) REFERENCES animals(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS birth_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      mother_id INT NOT NULL,
      father_id INT,
      birth_date DATE NOT NULL,
      gender VARCHAR(10),
      weight DECIMAL(10,2),
      health_status VARCHAR(50),
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (mother_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (father_id) REFERENCES animals(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS feeding_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      feed_type VARCHAR(100) NOT NULL,
      quantity DECIMAL(10,2) NOT NULL,
      unit VARCHAR(20),
      date DATE NOT NULL,
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS weight_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      date DATE NOT NULL,
      weight DECIMAL(10,2) NOT NULL,
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS vaccinations (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      vaccine_name VARCHAR(200) NOT NULL,
      vaccine_type VARCHAR(100),
      date DATE NOT NULL,
      next_due_date DATE,
      veterinarian INT,
      batch_number VARCHAR(100),
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (veterinarian) REFERENCES users(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS diseases (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      disease_name VARCHAR(200) NOT NULL,
      symptoms TEXT,
      severity VARCHAR(50) DEFAULT 'mild',
      date DATE NOT NULL,
      status VARCHAR(50) DEFAULT 'active',
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS treatments (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      disease_id INT,
      medicine VARCHAR(200) NOT NULL,
      dosage VARCHAR(100),
      duration VARCHAR(100),
      veterinarian INT,
      cost DECIMAL(12,2),
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (disease_id) REFERENCES diseases(id) ON DELETE SET NULL,
      FOREIGN KEY (veterinarian) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS pregnancies (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      breeding_record_id INT,
      pregnancy_date DATE NOT NULL,
      expected_delivery_date DATE,
      status VARCHAR(50) DEFAULT 'confirmed',
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (breeding_record_id) REFERENCES breeding_records(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS animal_transfers (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      from_location INT,
      to_location INT NOT NULL,
      date DATE NOT NULL,
      reason TEXT,
      approved_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (from_location) REFERENCES animal_locations(id) ON DELETE SET NULL,
      FOREIGN KEY (to_location) REFERENCES animal_locations(id) ON DELETE CASCADE,
      FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS animal_purchases (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      supplier_name VARCHAR(200),
      purchase_date DATE NOT NULL,
      cost DECIMAL(12,2),
      documents TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS animal_sales (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      customer_name VARCHAR(200),
      sale_date DATE NOT NULL,
      price DECIMAL(12,2),
      payment_status VARCHAR(50) DEFAULT 'pending',
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS animal_deaths (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      date DATE NOT NULL,
      cause VARCHAR(200),
      notes TEXT,
      reported_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (reported_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS animal_history (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      action VARCHAR(50) NOT NULL,
      description TEXT,
      changed_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS milk_storage_tanks (
      id INT AUTO_INCREMENT PRIMARY KEY,
      tank_name VARCHAR(100) NOT NULL,
      tank_number VARCHAR(50) UNIQUE NOT NULL,
      capacity_liters DECIMAL(10,2) NOT NULL,
      current_quantity DECIMAL(10,2) DEFAULT 0.00,
      temperature DECIMAL(5,2),
      status VARCHAR(50) DEFAULT 'available',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS milk_products (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      unit VARCHAR(20),
      price DECIMAL(12,2),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS milk_collections (
      id INT AUTO_INCREMENT PRIMARY KEY,
      collection_date DATE NOT NULL,
      time VARCHAR(50) NOT NULL,
      collector_id INT,
      branch_id INT,
      quantity_liters DECIMAL(10,2) NOT NULL,
      number_of_animals INT DEFAULT 0,
      average_per_animal DECIMAL(10,2),
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (collector_id) REFERENCES users(id) ON DELETE SET NULL,
      FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS milk_quality_tests (
      id INT AUTO_INCREMENT PRIMARY KEY,
      collection_id INT NOT NULL,
      fat_percentage DECIMAL(5,2),
      protein DECIMAL(5,2),
      temperature DECIMAL(5,2),
      color VARCHAR(20),
      smell VARCHAR(50),
      density DECIMAL(5,2),
      contamination BOOLEAN DEFAULT FALSE,
      quality_status VARCHAR(50) DEFAULT 'good',
      tested_by INT,
      test_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (collection_id) REFERENCES milk_collections(id) ON DELETE CASCADE,
      FOREIGN KEY (tested_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS milk_storage (
      id INT AUTO_INCREMENT PRIMARY KEY,
      tank_id INT NOT NULL,
      collection_id INT NOT NULL,
      quantity_liters DECIMAL(10,2) NOT NULL,
      production_date DATE,
      expiry_date DATE,
      quality_status VARCHAR(50),
      status VARCHAR(50) DEFAULT 'stored',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (tank_id) REFERENCES milk_storage_tanks(id) ON DELETE CASCADE,
      FOREIGN KEY (collection_id) REFERENCES milk_collections(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS milk_processing (
      id INT AUTO_INCREMENT PRIMARY KEY,
      collection_id INT NOT NULL,
      product_id INT NOT NULL,
      input_quantity DECIMAL(10,2) NOT NULL,
      output_quantity DECIMAL(10,2),
      processing_date DATE,
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (collection_id) REFERENCES milk_collections(id) ON DELETE CASCADE,
      FOREIGN KEY (product_id) REFERENCES milk_products(id) ON DELETE CASCADE,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS milk_waste (
      id INT AUTO_INCREMENT PRIMARY KEY,
      collection_id INT NOT NULL,
      quantity_liters DECIMAL(10,2) NOT NULL,
      reason VARCHAR(50) NOT NULL,
      date DATE NOT NULL,
      reported_by INT,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (collection_id) REFERENCES milk_collections(id) ON DELETE CASCADE,
      FOREIGN KEY (reported_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS inventory_categories (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS stock_locations (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      type VARCHAR(50) DEFAULT 'other',
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS supplier_categories (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS suppliers (
      id INT AUTO_INCREMENT PRIMARY KEY,
      category_id INT,
      supplier_name VARCHAR(100) NOT NULL,
      company_name VARCHAR(200),
      phone VARCHAR(20),
      email VARCHAR(100),
      address TEXT,
      registration_number VARCHAR(100),
      payment_terms VARCHAR(200),
      bank_name VARCHAR(200),
      bank_account VARCHAR(100),
      status VARCHAR(50) DEFAULT 'active',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (category_id) REFERENCES supplier_categories(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS inventory_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      category_id INT,
      name VARCHAR(200) NOT NULL,
      code VARCHAR(50) UNIQUE,
      barcode VARCHAR(100),
      description TEXT,
      unit VARCHAR(20),
      quantity DECIMAL(12,2) DEFAULT 0.00,
      min_stock_level DECIMAL(12,2) DEFAULT 0.00,
      max_stock_level DECIMAL(12,2) DEFAULT 0.00,
      purchase_price DECIMAL(12,2),
      selling_price DECIMAL(12,2),
      location_id INT,
      supplier_id INT,
      expiry_date DATE,
      storage_condition VARCHAR(200),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (category_id) REFERENCES inventory_categories(id) ON DELETE SET NULL,
      FOREIGN KEY (location_id) REFERENCES stock_locations(id) ON DELETE SET NULL,
      FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS feed_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      code VARCHAR(50),
      category VARCHAR(50),
      quantity DECIMAL(10,2) DEFAULT 0.00,
      unit VARCHAR(20),
      min_stock_level DECIMAL(10,2) DEFAULT 0,
      max_stock_level DECIMAL(10,2) DEFAULT 0,
      purchase_price DECIMAL(12,2) DEFAULT 0,
      expiry_date DATE,
      supplier_id INT,
      notes TEXT,
      supplier_name VARCHAR(200),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS medicine_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      brand VARCHAR(200),
      category VARCHAR(100),
      manufacturer VARCHAR(200),
      batch_number VARCHAR(100),
      expiry_date DATE,
      quantity DECIMAL(10,2) DEFAULT 0.00,
      unit VARCHAR(20),
      unit_price DECIMAL(12,2) DEFAULT 0,
      reorder_level DECIMAL(10,2) DEFAULT 0,
      storage_condition VARCHAR(200),
      supplier_id INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS equipment (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      model VARCHAR(200),
      category VARCHAR(50),
      serial_number VARCHAR(100) UNIQUE,
      purchase_date DATE,
      quantity DECIMAL(10,2) DEFAULT 1,
      item_condition VARCHAR(20) DEFAULT 'good',
      status VARCHAR(30) DEFAULT 'available',
      location VARCHAR(255),
      purchase_price DECIMAL(12,2) DEFAULT 0,
      location_id INT,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (location_id) REFERENCES stock_locations(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS equipment_maintenance (
      id INT AUTO_INCREMENT PRIMARY KEY,
      equipment_id INT NOT NULL,
      maintenance_type VARCHAR(100),
      description TEXT,
      date DATE,
      cost DECIMAL(12,2),
      service_provider VARCHAR(200),
      next_maintenance_date DATE,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS stock_transactions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      item_id INT NOT NULL,
      type VARCHAR(50) NOT NULL,
      reference_type VARCHAR(50),
      reference_id INT,
      quantity DECIMAL(12,2) NOT NULL,
      unit_price DECIMAL(12,2),
      total_price DECIMAL(12,2),
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS stock_issues (
      id INT AUTO_INCREMENT PRIMARY KEY,
      issue_number VARCHAR(50) UNIQUE NOT NULL,
      department_id INT,
      requested_by INT NOT NULL,
      approved_by INT,
      date DATE NOT NULL,
      notes TEXT,
      status VARCHAR(50) DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
      FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS stock_issue_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      issue_id INT NOT NULL,
      item_id INT NOT NULL,
      quantity DECIMAL(12,2) NOT NULL,
      unit_price DECIMAL(12,2),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (issue_id) REFERENCES stock_issues(id) ON DELETE CASCADE,
      FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS stock_transfers (
      id INT AUTO_INCREMENT PRIMARY KEY,
      transfer_number VARCHAR(50) UNIQUE NOT NULL,
      item_id INT NOT NULL,
      from_location INT,
      to_location INT NOT NULL,
      quantity DECIMAL(12,2) NOT NULL,
      date DATE NOT NULL,
      approved_by INT,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
      FOREIGN KEY (from_location) REFERENCES stock_locations(id) ON DELETE SET NULL,
      FOREIGN KEY (to_location) REFERENCES stock_locations(id) ON DELETE CASCADE,
      FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS stock_adjustments (
      id INT AUTO_INCREMENT PRIMARY KEY,
      adjustment_number VARCHAR(50) UNIQUE NOT NULL,
      item_id INT NOT NULL,
      current_quantity DECIMAL(12,2) NOT NULL,
      new_quantity DECIMAL(12,2) NOT NULL,
      difference DECIMAL(12,2) NOT NULL,
      reason VARCHAR(200) NOT NULL,
      approved_by INT,
      date DATE NOT NULL,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
      FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS feed_consumption (
      id INT AUTO_INCREMENT PRIMARY KEY,
      feed_item_id INT NOT NULL,
      animal_group_id INT,
      quantity DECIMAL(10,2) NOT NULL,
      date DATE NOT NULL,
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (feed_item_id) REFERENCES feed_items(id) ON DELETE CASCADE,
      FOREIGN KEY (animal_group_id) REFERENCES animal_groups(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS stock_audits (
      id INT AUTO_INCREMENT PRIMARY KEY,
      audit_number VARCHAR(50) UNIQUE NOT NULL,
      location_id INT,
      audit_date DATE NOT NULL,
      status VARCHAR(50) DEFAULT 'pending',
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (location_id) REFERENCES stock_locations(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS stock_audit_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      audit_id INT NOT NULL,
      item_id INT NOT NULL,
      system_quantity DECIMAL(12,2) NOT NULL,
      counted_quantity DECIMAL(12,2) NOT NULL,
      difference DECIMAL(12,2) NOT NULL,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (audit_id) REFERENCES stock_audits(id) ON DELETE CASCADE,
      FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS purchase_requests (
      id INT AUTO_INCREMENT PRIMARY KEY,
      request_number VARCHAR(50) UNIQUE NOT NULL,
      department_id INT,
      requested_by INT NOT NULL,
      priority VARCHAR(50) DEFAULT 'normal',
      status VARCHAR(50) DEFAULT 'pending',
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
      FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS purchase_request_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      request_id INT NOT NULL,
      item_name VARCHAR(200) NOT NULL,
      description TEXT,
      quantity DECIMAL(10,2) NOT NULL,
      unit VARCHAR(20),
      estimated_price DECIMAL(12,2),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (request_id) REFERENCES purchase_requests(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS purchase_approvals (
      id INT AUTO_INCREMENT PRIMARY KEY,
      request_id INT NOT NULL,
      approved_by INT NOT NULL,
      approval_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      status VARCHAR(50) NOT NULL,
      comments TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (request_id) REFERENCES purchase_requests(id) ON DELETE CASCADE,
      FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS purchase_quotations (
      id INT AUTO_INCREMENT PRIMARY KEY,
      supplier_id INT NOT NULL,
      request_id INT NOT NULL,
      quotation_number VARCHAR(50) UNIQUE NOT NULL,
      total_amount DECIMAL(12,2),
      delivery_time VARCHAR(100),
      valid_until DATE,
      document_url VARCHAR(500),
      status VARCHAR(50) DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
      FOREIGN KEY (request_id) REFERENCES purchase_requests(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS purchase_quotation_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      quotation_id INT NOT NULL,
      item_name VARCHAR(200) NOT NULL,
      description TEXT,
      quantity DECIMAL(10,2) NOT NULL,
      unit VARCHAR(20),
      unit_price DECIMAL(12,2),
      total_price DECIMAL(12,2),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (quotation_id) REFERENCES purchase_quotations(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS purchase_orders (
      id INT AUTO_INCREMENT PRIMARY KEY,
      po_number VARCHAR(50) UNIQUE NOT NULL,
      supplier_id INT NOT NULL,
      request_id INT,
      quotation_id INT,
      order_date DATE NOT NULL,
      expected_delivery DATE,
      status VARCHAR(50) DEFAULT 'draft',
      notes TEXT,
      created_by INT,
      approved_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
      FOREIGN KEY (request_id) REFERENCES purchase_requests(id) ON DELETE SET NULL,
      FOREIGN KEY (quotation_id) REFERENCES purchase_quotations(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
      FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS purchase_order_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      po_id INT NOT NULL,
      item_name VARCHAR(200) NOT NULL,
      description TEXT,
      quantity DECIMAL(10,2) NOT NULL,
      unit VARCHAR(20),
      unit_price DECIMAL(12,2),
      total_price DECIMAL(12,2),
      received_quantity DECIMAL(10,2) DEFAULT 0.00,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (po_id) REFERENCES purchase_orders(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS goods_receipts (
      id INT AUTO_INCREMENT PRIMARY KEY,
      receipt_number VARCHAR(50) UNIQUE NOT NULL,
      po_id INT NOT NULL,
      supplier_id INT NOT NULL,
      received_date DATE NOT NULL,
      received_by INT,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (po_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
      FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
      FOREIGN KEY (received_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS goods_receipt_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      receipt_id INT NOT NULL,
      po_item_id INT,
      item_name VARCHAR(200) NOT NULL,
      quantity_received DECIMAL(10,2) NOT NULL,
      quantity_ordered DECIMAL(10,2),
      condition_notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (receipt_id) REFERENCES goods_receipts(id) ON DELETE CASCADE,
      FOREIGN KEY (po_item_id) REFERENCES purchase_order_items(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS supplier_invoices (
      id INT AUTO_INCREMENT PRIMARY KEY,
      invoice_number VARCHAR(50) UNIQUE NOT NULL,
      supplier_id INT NOT NULL,
      po_id INT,
      amount DECIMAL(12,2),
      tax DECIMAL(12,2) DEFAULT 0.00,
      total DECIMAL(12,2),
      due_date DATE,
      status VARCHAR(50) DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
      FOREIGN KEY (po_id) REFERENCES purchase_orders(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS supplier_payments (
      id INT AUTO_INCREMENT PRIMARY KEY,
      invoice_id INT NOT NULL,
      amount DECIMAL(12,2) NOT NULL,
      payment_date DATE NOT NULL,
      payment_method VARCHAR(50),
      reference_number VARCHAR(100),
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (invoice_id) REFERENCES supplier_invoices(id) ON DELETE CASCADE,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS supplier_ratings (
      id INT AUTO_INCREMENT PRIMARY KEY,
      supplier_id INT NOT NULL,
      product_quality INT DEFAULT 0,
      delivery_time INT DEFAULT 0,
      price INT DEFAULT 0,
      reliability INT DEFAULT 0,
      comments TEXT,
      rated_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
      FOREIGN KEY (rated_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS supplier_contracts (
      id INT AUTO_INCREMENT PRIMARY KEY,
      contract_number VARCHAR(50) UNIQUE NOT NULL,
      supplier_id INT NOT NULL,
      start_date DATE NOT NULL,
      end_date DATE,
      terms TEXT,
      total_value DECIMAL(12,2),
      document_url VARCHAR(500),
      status VARCHAR(50) DEFAULT 'active',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS vehicle_types (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS vehicles (
      id INT AUTO_INCREMENT PRIMARY KEY,
      vehicle_name VARCHAR(100) NOT NULL,
      type_id INT,
      plate_number VARCHAR(50) UNIQUE NOT NULL,
      model VARCHAR(100),
      manufacturer VARCHAR(100),
      year INT,
      engine_number VARCHAR(100),
      chassis_number VARCHAR(100),
      capacity DECIMAL(10,2),
      fuel_type VARCHAR(50),
      status VARCHAR(50) DEFAULT 'available',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (type_id) REFERENCES vehicle_types(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS drivers (
      id INT AUTO_INCREMENT PRIMARY KEY,
      first_name VARCHAR(100) NOT NULL,
      last_name VARCHAR(100) NOT NULL,
      phone VARCHAR(20),
      email VARCHAR(100),
      national_id VARCHAR(50) UNIQUE,
      license_number VARCHAR(50) UNIQUE,
      license_type VARCHAR(50),
      license_expiry DATE,
      status VARCHAR(50) DEFAULT 'available',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL
    )`,
    `CREATE TABLE IF NOT EXISTS transport_requests (
      id INT AUTO_INCREMENT PRIMARY KEY,
      request_number VARCHAR(50) UNIQUE NOT NULL,
      department_id INT,
      requested_by INT NOT NULL,
      pickup_location TEXT NOT NULL,
      destination TEXT NOT NULL,
      required_date DATE,
      description TEXT,
      priority VARCHAR(50) DEFAULT 'normal',
      status VARCHAR(50) DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
      FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS transport_approvals (
      id INT AUTO_INCREMENT PRIMARY KEY,
      request_id INT NOT NULL,
      approved_by INT NOT NULL,
      approval_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      status VARCHAR(50) NOT NULL,
      comments TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (request_id) REFERENCES transport_requests(id) ON DELETE CASCADE,
      FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS trips (
      id INT AUTO_INCREMENT PRIMARY KEY,
      trip_number VARCHAR(50) UNIQUE NOT NULL,
      request_id INT,
      vehicle_id INT,
      driver_id INT,
      start_time TIMESTAMP NULL,
      end_time TIMESTAMP NULL,
      distance_km DECIMAL(10,2),
      status VARCHAR(50) DEFAULT 'scheduled',
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (request_id) REFERENCES transport_requests(id) ON DELETE SET NULL,
      FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL,
      FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS deliveries (
      id INT AUTO_INCREMENT PRIMARY KEY,
      delivery_number VARCHAR(50) UNIQUE NOT NULL,
      trip_id INT,
      customer_name VARCHAR(200),
      customer_address TEXT,
      contact_phone VARCHAR(20),
      delivery_date DATE,
      status VARCHAR(50) DEFAULT 'pending',
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS delivery_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      delivery_id INT NOT NULL,
      item_name VARCHAR(200) NOT NULL,
      quantity DECIMAL(10,2) NOT NULL,
      unit VARCHAR(20),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (delivery_id) REFERENCES deliveries(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS fuel_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      vehicle_id INT NOT NULL,
      driver_id INT,
      fuel_type VARCHAR(50),
      quantity DECIMAL(10,2) NOT NULL,
      cost DECIMAL(12,2) NOT NULL,
      date DATE NOT NULL,
      mileage DECIMAL(10,2),
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,
      FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS vehicle_maintenance (
      id INT AUTO_INCREMENT PRIMARY KEY,
      vehicle_id INT NOT NULL,
      maintenance_type VARCHAR(50) DEFAULT 'other',
      description TEXT,
      date DATE NOT NULL,
      cost DECIMAL(12,2),
      service_provider VARCHAR(200),
      next_service_date DATE,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS account_types (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS accounts (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      code VARCHAR(20) UNIQUE NOT NULL,
      type VARCHAR(50) NOT NULL,
      description TEXT,
      balance DECIMAL(12,2) DEFAULT 0.00,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS expense_categories (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS customers (
      id INT AUTO_INCREMENT PRIMARY KEY,
      customer_code VARCHAR(50) UNIQUE NOT NULL,
      first_name VARCHAR(100) NOT NULL,
      last_name VARCHAR(100) NOT NULL,
      company_name VARCHAR(200),
      phone VARCHAR(20),
      email VARCHAR(100),
      address TEXT,
      customer_type VARCHAR(50) DEFAULT 'individual',
      registration_number VARCHAR(100),
      credit_limit DECIMAL(12,2) DEFAULT 0.00,
      payment_terms VARCHAR(200),
      balance DECIMAL(12,2) DEFAULT 0.00,
      status VARCHAR(50) DEFAULT 'active',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL
    )`,
    `CREATE TABLE IF NOT EXISTS customer_payments (
      id INT AUTO_INCREMENT PRIMARY KEY,
      customer_id INT,
      invoice_id INT,
      amount DECIMAL(12,2) NOT NULL,
      payment_method VARCHAR(50),
      reference_number VARCHAR(100),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS income_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      income_number VARCHAR(50) UNIQUE NOT NULL,
      source VARCHAR(200) NOT NULL,
      customer_id INT,
      amount DECIMAL(12,2) NOT NULL,
      payment_method VARCHAR(50),
      date DATE NOT NULL,
      description TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS expense_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      expense_number VARCHAR(50) UNIQUE NOT NULL,
      category_id INT,
      description TEXT,
      amount DECIMAL(12,2) NOT NULL,
      date DATE NOT NULL,
      department_id INT,
      attachment_url VARCHAR(500),
      approved_by INT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (category_id) REFERENCES expense_categories(id) ON DELETE SET NULL,
      FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
      FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS invoices (
      id INT AUTO_INCREMENT PRIMARY KEY,
      invoice_number VARCHAR(50) UNIQUE NOT NULL,
      customer_id INT,
      type VARCHAR(50) NOT NULL,
      total_amount DECIMAL(12,2),
      tax DECIMAL(12,2) DEFAULT 0.00,
      due_date DATE,
      status VARCHAR(50) DEFAULT 'draft',
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS invoice_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      invoice_id INT NOT NULL,
      description VARCHAR(500) NOT NULL,
      quantity DECIMAL(10,2) NOT NULL,
      unit_price DECIMAL(12,2) NOT NULL,
      total_price DECIMAL(12,2) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS receipts (
      id INT AUTO_INCREMENT PRIMARY KEY,
      receipt_number VARCHAR(50) UNIQUE NOT NULL,
      invoice_id INT,
      customer_id INT,
      amount DECIMAL(12,2) NOT NULL,
      payment_method VARCHAR(50),
      reference_number VARCHAR(100),
      date DATE NOT NULL,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL,
      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS payments (
      id INT AUTO_INCREMENT PRIMARY KEY,
      payment_number VARCHAR(50) UNIQUE NOT NULL,
      invoice_id INT,
      supplier_id INT,
      amount DECIMAL(12,2) NOT NULL,
      payment_method VARCHAR(50),
      payment_date DATE NOT NULL,
      reference_number VARCHAR(100),
      status VARCHAR(50) DEFAULT 'pending',
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL,
      FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS payroll_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      payroll_number VARCHAR(50) UNIQUE NOT NULL,
      month VARCHAR(7) NOT NULL,
      total_gross DECIMAL(12,2) DEFAULT 0.00,
      total_deductions DECIMAL(12,2) DEFAULT 0.00,
      total_net DECIMAL(12,2) DEFAULT 0.00,
      status VARCHAR(50) DEFAULT 'draft',
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS payroll_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      payroll_id INT NOT NULL,
      employee_id INT NOT NULL,
      basic_salary DECIMAL(12,2),
      allowances DECIMAL(12,2) DEFAULT 0.00,
      deductions DECIMAL(12,2) DEFAULT 0.00,
      net_salary DECIMAL(12,2),
      status VARCHAR(50) DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (payroll_id) REFERENCES payroll_records(id) ON DELETE CASCADE,
      FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS budgets (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      department_id INT,
      fiscal_year VARCHAR(10),
      total_amount DECIMAL(12,2),
      status VARCHAR(50) DEFAULT 'draft',
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS budget_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      budget_id INT NOT NULL,
      category_id INT,
      planned_amount DECIMAL(12,2),
      actual_amount DECIMAL(12,2) DEFAULT 0.00,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (budget_id) REFERENCES budgets(id) ON DELETE CASCADE,
      FOREIGN KEY (category_id) REFERENCES expense_categories(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS tax_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      tax_type VARCHAR(100) NOT NULL,
      rate DECIMAL(5,2) NOT NULL,
      amount DECIMAL(12,2) NOT NULL,
      period VARCHAR(20),
      due_date DATE,
      payment_date DATE,
      status VARCHAR(50) DEFAULT 'pending',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS transactions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      account_id INT NOT NULL,
      type VARCHAR(50) NOT NULL,
      amount DECIMAL(12,2) NOT NULL,
      description TEXT,
      reference_type VARCHAR(50),
      reference_id INT,
      transaction_date DATE NOT NULL,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS product_categories (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS products (
      id INT AUTO_INCREMENT PRIMARY KEY,
      category_id INT,
      name VARCHAR(200) NOT NULL,
      code VARCHAR(50) UNIQUE,
      barcode VARCHAR(100),
      unit VARCHAR(20),
      price DECIMAL(12,2),
      cost_price DECIMAL(12,2),
      quantity_available DECIMAL(12,2) DEFAULT 0.00,
      description TEXT,
      status VARCHAR(50) DEFAULT 'active',
      image_url VARCHAR(500),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (category_id) REFERENCES product_categories(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS sales_orders (
      id INT AUTO_INCREMENT PRIMARY KEY,
      order_number VARCHAR(50) UNIQUE NOT NULL,
      customer_id INT,
      order_date DATE NOT NULL,
      status VARCHAR(50) DEFAULT 'pending',
      total_amount DECIMAL(12,2),
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS sales_order_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      order_id INT NOT NULL,
      product_id INT,
      quantity DECIMAL(10,2) NOT NULL,
      unit_price DECIMAL(12,2) NOT NULL,
      total_price DECIMAL(12,2) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE CASCADE,
      FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS sales_quotations (
      id INT AUTO_INCREMENT PRIMARY KEY,
      quotation_number VARCHAR(50) UNIQUE NOT NULL,
      customer_id INT,
      valid_until DATE,
      status VARCHAR(50) DEFAULT 'draft',
      total_amount DECIMAL(12,2),
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS sales_quotation_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      quotation_id INT NOT NULL,
      product_id INT,
      quantity DECIMAL(10,2) NOT NULL,
      unit_price DECIMAL(12,2) NOT NULL,
      total_price DECIMAL(12,2) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (quotation_id) REFERENCES sales_quotations(id) ON DELETE CASCADE,
      FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS sales_returns (
      id INT AUTO_INCREMENT PRIMARY KEY,
      return_number VARCHAR(50) UNIQUE NOT NULL,
      order_id INT,
      customer_id INT,
      return_date DATE NOT NULL,
      reason TEXT,
      status VARCHAR(50) DEFAULT 'pending',
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE SET NULL,
      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS sales_return_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      return_id INT NOT NULL,
      product_id INT,
      quantity DECIMAL(10,2) NOT NULL,
      reason TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (return_id) REFERENCES sales_returns(id) ON DELETE CASCADE,
      FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS sales_invoices (
      id INT AUTO_INCREMENT PRIMARY KEY,
      invoice_number VARCHAR(50) UNIQUE NOT NULL,
      customer_id INT,
      order_id INT,
      subtotal DECIMAL(12,2),
      tax DECIMAL(12,2) DEFAULT 0.00,
      total_amount DECIMAL(12,2),
      invoice_date DATE NOT NULL,
      due_date DATE,
      status VARCHAR(50) DEFAULT 'pending',
      notes TEXT,
      created_by INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
      FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE SET NULL,
      FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS sales_invoice_items (
      id INT AUTO_INCREMENT PRIMARY KEY,
      invoice_id INT NOT NULL,
      product_id INT,
      description VARCHAR(500),
      quantity DECIMAL(10,2) NOT NULL,
      unit_price DECIMAL(12,2) NOT NULL,
      total_price DECIMAL(12,2) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (invoice_id) REFERENCES sales_invoices(id) ON DELETE CASCADE,
      FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS animal_health_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      checkup_date DATE NOT NULL,
      veterinarian INT,
      diagnosis TEXT,
      prescription TEXT,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (veterinarian) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS vaccination_schedule (
      id INT AUTO_INCREMENT PRIMARY KEY,
      vaccine_name VARCHAR(200) NOT NULL,
      description TEXT,
      frequency_days INT,
      animal_category_id INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_category_id) REFERENCES animal_categories(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS vaccination_records (
      id INT AUTO_INCREMENT PRIMARY KEY,
      animal_id INT NOT NULL,
      schedule_id INT,
      vaccination_date DATE NOT NULL,
      next_due_date DATE,
      veterinarian INT,
      batch_number VARCHAR(100),
      cost DECIMAL(12,2),
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE CASCADE,
      FOREIGN KEY (schedule_id) REFERENCES vaccination_schedule(id) ON DELETE SET NULL,
      FOREIGN KEY (veterinarian) REFERENCES users(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS treatment_prescriptions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      treatment_id INT NOT NULL,
      medicine_item_id INT,
      dosage VARCHAR(100),
      duration VARCHAR(100),
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (treatment_id) REFERENCES treatments(id) ON DELETE CASCADE,
      FOREIGN KEY (medicine_item_id) REFERENCES medicine_items(id) ON DELETE SET NULL
    )`,
    `CREATE TABLE IF NOT EXISTS crop_types (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      description TEXT,
      \`usage\` VARCHAR(255),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL
    )`,
    `CREATE TABLE IF NOT EXISTS land_areas (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      area_size DECIMAL(10,2) NOT NULL,
      location VARCHAR(255),
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL
    )`,
    `CREATE TABLE IF NOT EXISTS crop_activities (
      id INT AUTO_INCREMENT PRIMARY KEY,
      crop_type_id INT NOT NULL,
      land_area_id INT NOT NULL,
      planting_date DATE,
      harvest_date DATE,
      quantity_planted DECIMAL(10,2) DEFAULT 0,
      quantity_harvested DECIMAL(10,2) DEFAULT 0,
      status VARCHAR(50) DEFAULT 'planted',
      diseases TEXT,
      sales_amount DECIMAL(12,2) DEFAULT 0,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (crop_type_id) REFERENCES crop_types(id) ON DELETE CASCADE,
      FOREIGN KEY (land_area_id) REFERENCES land_areas(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS app_settings (
      id INT AUTO_INCREMENT PRIMARY KEY,
      setting_key VARCHAR(100) UNIQUE NOT NULL,
      setting_value LONGTEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS employee_shifts (
      id INT AUTO_INCREMENT PRIMARY KEY,
      employee_id INT NOT NULL,
      department_id INT NOT NULL,
      shift_name VARCHAR(100) NOT NULL,
      start_time TIME NOT NULL,
      end_time TIME NOT NULL,
      working_days TEXT,
      assigned_by INT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (employee_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
      FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS employee_activities (
      id INT AUTO_INCREMENT PRIMARY KEY,
      employee_id INT NOT NULL,
      date DATE NOT NULL,
      task_description TEXT,
      issue_description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
    )`,
  ];

  for (const q of queries) {
    await conn.query(q);
  }
}
